'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useViewer, buttonClass, primaryClass } from './ExploreShell.tsx';
import { memberRequest } from '../../lib/workspace-data.ts';
import { object, errorMessage, formatDate, typeNames } from '../../lib/explore-data.ts';
type Row = { id: string; title: string; record_type: keyof typeof typeNames; state: string; draft_version: number; record_version: number; updated_at: string; has_unapplied_changes: boolean };
function rows(value: unknown): Row[] { if (!Array.isArray(value)) throw new Error('아카이브 응답을 확인하지 못했습니다.'); return value.map(value => { const row = object(value); if (typeof row.id !== 'string' || !/^[0-9a-f-]{36}$/i.test(row.id) || typeof row.title !== 'string' || !Object.hasOwn(typeNames, String(row.record_type)) || typeof row.state !== 'string' || typeof row.updated_at !== 'string' || !Number.isSafeInteger(row.draft_version) || !Number.isSafeInteger(row.record_version) || typeof row.has_unapplied_changes !== 'boolean') throw new Error('아카이브 응답을 확인하지 못했습니다.'); return row as Row; }); }
export default function Archive() {
  const viewer = useViewer(); const [query, setQuery] = useState(''), [state, setState] = useState('all'), [search, setSearch] = useState({ query: '', state: 'all' }), [offset, setOffset] = useState(0), [items, setItems] = useState<Row[]>([]), [more, setMore] = useState(false), [busy, setBusy] = useState(true), [mutation, setMutation] = useState(false), [error, setError] = useState(''), [revision, setRevision] = useState(0), [repository, setRepository] = useState('');
  useEffect(() => { let active = true; setBusy(true); setError('');
    void memberRequest(viewer.id!, `/api/archive?${new URLSearchParams({ q: search.query, state: search.state, offset: String(offset) })}`).then(result => { if (!active) return; const next = rows(result.data), page = object(result.page); if (typeof page.has_more !== 'boolean') throw new Error('페이지 응답을 확인하지 못했습니다.'); setItems(previous => offset ? [...previous, ...next.filter(row => !previous.some(item => item.id === row.id))] : next); setMore(page.has_more); }).catch(error => { if (active) setError(errorMessage(error)); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; };
  }, [viewer.id, search, offset, revision]);
  async function action(row: Row) { if (!window.confirm(row.state === 'deleted' ? '이 기록을 비공개 상태로 복원할까요?' : '이 기록을 휴지통으로 이동할까요?')) return; setMutation(true); setError(''); try { await memberRequest(viewer.id!, `/api/drafts/${row.id}${row.state === 'deleted' ? '/restore' : ''}`, row.state === 'deleted' ? 'POST' : 'DELETE', { draft_version: row.draft_version, record_version: row.record_version }); setOffset(0); setItems([]); setRevision(value => value + 1); } catch (error) { setError(errorMessage(error)); } finally { setMutation(false); } }
  async function importRepository() { setMutation(true); setError(''); try { const result = await memberRequest(viewer.id!, '/api/imports/github', 'POST', { url: repository }); const draft = object(result.data); if (typeof draft.id !== 'string' || !/^[0-9a-f-]{36}$/i.test(draft.id)) throw new Error('가져오기 응답을 확인하지 못했습니다.'); window.location.assign(`/write?id=${draft.id}`); } catch (error) { setError(errorMessage(error)); setMutation(false); } }
  return <main id="main" className="mx-auto max-w-6xl px-5 pt-12 sm:px-8"><p className="text-xs font-mono text-zinc-500">내 기록</p><div className="mt-3 mb-8 flex flex-wrap justify-between gap-4"><h1 className="text-3xl font-semibold">내 아카이브</h1><Link href="/write" className={primaryClass}>새 기록 작성</Link></div>
    <form className="mb-7 flex flex-wrap gap-3" onSubmit={event => { event.preventDefault(); setItems([]); setOffset(0); setSearch({ query, state }); }}><label className="min-w-48 flex-1"><span className="sr-only">내 기록 검색</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="제목·본문 검색" className="w-full rounded-md border border-zinc-200 p-3 text-sm" /></label><label><span className="sr-only">기록 상태</span><select className="rounded-md border border-zinc-200 p-3 text-sm" value={state} onChange={event => setState(event.target.value)}>{Object.entries({ all: '전체', draft: '초안', public: '공개', private: '비공개', deleted: '휴지통' }).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button className={buttonClass} type="submit">검색</button></form>
    {error && <div role="alert" className="mb-5 text-sm"><p>{error}</p><button type="button" className={`${buttonClass} mt-3`} onClick={() => setRevision(value => value + 1)}>다시 불러오기</button></div>}
    <div className="divide-y divide-zinc-200 rounded-md border border-zinc-200">{items.map(row => <section key={row.id} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="mb-2 text-xs text-zinc-500">{typeNames[row.record_type]} · {({ draft: '초안', public: '공개', private: '비공개', deleted: '휴지통' } as Record<string, string>)[row.state]} {row.has_unapplied_changes && '· 아직 반영하지 않은 수정 있음'}</p>{row.state === 'deleted' ? <h2>{row.title || '제목 없는 기록'}</h2> : <Link className="font-semibold hover:underline" href={`/write?id=${row.id}`}>{row.title || '제목 없는 기록'}</Link>}<p className="mt-2 text-xs font-mono text-zinc-500">{formatDate(row.updated_at)}</p></div><button type="button" className={buttonClass} disabled={mutation} onClick={() => void action(row)}>{row.state === 'deleted' ? '복원' : '휴지통으로 이동'}</button></section>)}{!items.length && !busy && <p className="p-8 text-sm text-zinc-500">조건에 맞는 기록이 없습니다.</p>}</div>
    {busy && <p role="status" className="mt-5 text-sm text-zinc-500">기록을 불러오는 중입니다.</p>}{more && !busy && !error && <button type="button" className={`${buttonClass} mt-5`} onClick={() => setOffset(value => value + 20)}>더 보기</button>}
    <form onSubmit={event => { event.preventDefault(); void importRepository(); }} className="mt-10 rounded-md border border-zinc-200 p-5"><h2 className="mb-3 font-semibold">GitHub 프로젝트 가져오기</h2><p className="mb-4 text-sm text-zinc-500">GitHub 저장소의 소개와 README를 가져옵니다. 가져온 글은 초안으로 저장됩니다.</p><div className="flex flex-wrap gap-3"><label className="min-w-48 flex-1"><span className="sr-only">GitHub 저장소 주소</span><input required type="url" value={repository} onChange={event => setRepository(event.target.value)} placeholder="https://github.com/owner/repository" className="w-full rounded-md border border-zinc-200 p-3 text-sm" /></label><button disabled={mutation} type="submit" className={buttonClass}>가져오기</button></div></form>
  </main>;
}
