'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useViewer,buttonClass } from './ExploreShell.tsx';
import { memberRequest } from '../../lib/workspace-data.ts';
import { errorMessage, object, typeNames } from '../../lib/explore-data.ts';
import { recordPage, type RecordRow } from '../../lib/portfolio-data.ts';
export default function Bookmarks() {
  const viewer=useViewer(); const [items,setItems]=useState<RecordRow[]>([]),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[query,setQuery]=useState(''),[type,setType]=useState(''),[search,setSearch]=useState({q:'',type:''}),[pending,setPending]=useState<string>();
  useEffect(()=>{let active=true;setLoading(true);setError('');void memberRequest(viewer.id!,`/api/bookmarks?${new URLSearchParams({q:search.q,...(search.type?{type:search.type}:{}),offset:String(offset)})}`).then(result=>{const page=recordPage(result);if(active){setItems(previous=>offset?[...previous,...page.rows.filter(row=>!previous.some(item=>item.id===row.id))]:page.rows);setMore(page.more);}}).catch(error=>{if(active)setError(errorMessage(error));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[viewer.id,search,offset,revision]);
  async function remove(row:RecordRow){setPending(row.id);setNotice('');try{const result=object((await memberRequest(viewer.id!,`/api/bookmarks/${row.id}`,'DELETE')).data);if(result.record_id!==row.id || result.saved!==false)throw new Error('보관 해제 결과를 확인하지 못했습니다.');setNotice('보관을 해제했습니다.');setOffset(0);setRevision(value=>value+1);}catch(error){setNotice(errorMessage(error));}finally{setPending(undefined);}}
  return <main id="main" className="mx-auto max-w-6xl px-5 py-12"><h1 className="mb-8 text-3xl font-semibold">보관함</h1><form className="mb-6 flex flex-wrap gap-3" onSubmit={event=>{event.preventDefault();setOffset(0);setItems([]);setSearch({q:query,type});setRevision(value=>value+1);}}><label className="min-w-0 flex-1"><span className="sr-only">보관한 글 제목 검색</span><input className="w-full rounded-md border border-zinc-200 p-3 text-sm" maxLength={100} placeholder="보관한 글 제목 검색" value={query} onChange={event=>setQuery(event.target.value)}/></label><label><span className="sr-only">글 종류</span><select className="rounded-md border border-zinc-200 p-3 text-sm" value={type} onChange={event=>setType(event.target.value)}><option value="">전체</option>{Object.entries(typeNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><button type="submit" className={buttonClass} disabled={!!pending}>검색</button><button type="button" className={buttonClass} disabled={!!pending} onClick={()=>{setQuery('');setType('');setOffset(0);setItems([]);setSearch({q:'',type:''});}}>초기화</button></form>
    {notice && <p role="status" className="mb-4 text-sm">{notice}</p>}{error && <div role="alert"><p>{error}</p><button type="button" className={buttonClass} onClick={()=>setRevision(value=>value+1)}>다시 시도</button></div>}
    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{items.map(row=><article key={row.id} className="rounded-md border border-zinc-200 p-5"><p className="mb-3 text-xs text-zinc-500">{typeNames[row.record_type]}</p><Link className="font-semibold hover:underline" href={`/records/${row.id}`}>{row.title}</Link><p className="my-4 line-clamp-2 text-sm text-zinc-600">{row.excerpt}</p><button type="button" disabled={!!pending} className={buttonClass} onClick={()=>void remove(row)}>{pending===row.id?'해제 중…':'보관 해제'}</button></article>)}</div>{loading && <p role="status">불러오는 중입니다.</p>}{!loading && !error && !items.length && <p className="text-sm text-zinc-500">{search.q||search.type?'검색 조건에 맞는 글이 없습니다.':'보관한 글이 없습니다.'}</p>}{more && !loading && !error && <button type="button" disabled={!!pending} className={`${buttonClass} mt-5`} onClick={()=>setOffset(value=>value+20)}>더 보기</button>}
  </main>;
}
