'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useViewer, buttonClass, primaryClass } from './ExploreShell.tsx';
import { memberRequest } from '../../lib/workspace-data.ts';
import { errorMessage } from '../../lib/explore-data.ts';
import { recordRows, recordPage, movePin, type RecordRow } from '../../lib/portfolio-data.ts';
export default function PinManager() {
  const viewer = useViewer(); const [pins,setPins] = useState<RecordRow[]>([]), [items,setItems] = useState<RecordRow[]>([]), [offset,setOffset] = useState(0), [more,setMore] = useState(false), [loading,setLoading] = useState(true), [busy,setBusy] = useState(false), [error,setError] = useState(''), [notice,setNotice] = useState(''), [revision,setRevision] = useState(0);
  useEffect(() => { let active = true; setLoading(true); setError(''); void Promise.all([memberRequest(viewer.id!, '/api/pins'), memberRequest(viewer.id!, `/api/archive?state=public&type=project&offset=${offset}`)]).then(([saved,records]) => { const next = recordPage(records), selected = recordRows(saved.data); if (active) { setPins(selected); setItems(previous => offset ? [...previous,...next.rows.filter(row => !previous.some(item => item.id === row.id))] : next.rows); setMore(next.more); } }).catch(error => { if(active) setError(errorMessage(error)); }).finally(() => { if(active) setLoading(false); }); return () => { active = false; }; }, [viewer.id,offset,revision]);
  async function persist(ids: string[]) { setBusy(true); setError(''); setNotice(''); try { const result = await memberRequest(viewer.id!, '/api/pins','PUT',{record_ids:ids}); setPins(recordRows(result.data)); setNotice('대표 프로젝트를 저장했습니다.'); } catch(error) { setError(errorMessage(error)); } finally { setBusy(false); } }
  return <main id="main" className="mx-auto max-w-4xl px-5 py-12"><h1 className="text-3xl font-semibold">대표 프로젝트</h1><p className="my-5 text-sm text-zinc-600">공개한 프로젝트 중 최대 3개를 선택하세요. 위에서부터 포트폴리오에 표시됩니다.</p>{error && <div role="alert"><p>{error}</p><button type="button" disabled={busy} className={buttonClass} onClick={() => setRevision(value => value+1)}>다시 불러오기</button></div>}{notice && <p role="status">{notice}</p>}
    <ol className="my-6 space-y-3">{pins.map((row,index) => <li key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-zinc-200 p-4"><Link href={`/records/${row.id}`} className="font-semibold">{index+1}. {row.title}</Link><div className="flex gap-2"><button type="button" className={buttonClass} disabled={busy || loading || index===0} aria-label={`${row.title} 위로`} onClick={() => void persist(movePin(pins.map(row=>row.id),index,-1))}>위로</button><button type="button" className={buttonClass} disabled={busy || loading || index===pins.length-1} aria-label={`${row.title} 아래로`} onClick={() => void persist(movePin(pins.map(row=>row.id),index,1))}>아래로</button><button type="button" className={buttonClass} disabled={busy || loading} onClick={() => void persist(pins.filter(item=>item.id!==row.id).map(item=>item.id))}>해제</button></div></li>)}</ol>
    <h2 className="mb-4 font-semibold">공개 프로젝트</h2><div className="space-y-3">{items.map(row => <div key={row.id} className="flex flex-wrap justify-between gap-3 rounded-md border border-zinc-200 p-4"><Link href={`/records/${row.id}`}>{row.title}</Link><button type="button" className={primaryClass} disabled={busy || loading || pins.length>=3 || pins.some(item=>item.id===row.id)} onClick={() => void persist([...pins.map(item=>item.id),row.id])}>{pins.some(item=>item.id===row.id) ? '선택됨' : '대표로 선택'}</button></div>)}</div>{loading && <p role="status">불러오는 중입니다.</p>}{!loading && !error && !items.length && <p className="text-sm text-zinc-500">공개한 프로젝트가 없습니다. 먼저 프로젝트를 공개해주세요.</p>}{more && !loading && !error && <button type="button" className={`${buttonClass} mt-4`} disabled={busy} onClick={() => setOffset(value=>value+20)}>더 보기</button>}
  </main>;
}
