'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { useViewer,buttonClass } from './ExploreShell.tsx';
import { memberRequest } from '../../lib/workspace-data.ts';
import { errorMessage,object } from '../../lib/explore-data.ts';
import { recordPage,type RecordRow } from '../../lib/portfolio-data.ts';
export default function RecordLinks({id,type,disabled}:{id:string;type:'project'|'study'|'other';disabled:boolean}) {
  const viewer=useViewer();const [related,setRelated]=useState<RecordRow[]>([]),[candidates,setCandidates]=useState<RecordRow[]>([]),[offset,setOffset]=useState(0),[relatedOffset,setRelatedOffset]=useState(0),[more,setMore]=useState(false),[relatedMore,setRelatedMore]=useState(false),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
  useEffect(()=>{if(type==='other')return;let active=true;setLoading(true);setError('');void Promise.all([memberRequest(viewer.id!,`/api/drafts/${id}/related?offset=${relatedOffset}`),memberRequest(viewer.id!,`/api/archive?${new URLSearchParams({type:type==='project'?'study':'project',q:search,offset:String(offset)})}`)]).then(([links,records])=>{const linked=recordPage(links),page=recordPage(records);if(active){setRelated(previous=>relatedOffset?[...previous,...linked.rows.filter(row=>!previous.some(item=>item.id===row.id))]:linked.rows);setCandidates(previous=>offset?[...previous,...page.rows.filter(row=>!previous.some(item=>item.id===row.id))]:page.rows);setMore(page.more);setRelatedMore(linked.more);}}).catch(error=>{if(active)setError(errorMessage(error));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[viewer.id,id,type,offset,relatedOffset,search,revision]);
  async function change(row:RecordRow,linked:boolean){setBusy(true);setError('');try{const input={project_id:type==='project'?id:row.id,study_id:type==='study'?id:row.id};const result=object((await memberRequest(viewer.id!,'/api/links',linked?'PUT':'DELETE',input)).data);if(result.project_id!==input.project_id||result.study_id!==input.study_id||result.linked!==linked)throw new Error('연결 결과를 확인하지 못했습니다.');setOffset(0);setRelatedOffset(0);setRevision(value=>value+1);}catch(error){setError(errorMessage(error));}finally{setBusy(false);}}
  if(type==='other')return null;
  return <section className="mt-8 rounded-md border border-zinc-200 p-5"><h2 className="font-semibold">{type==='project'?'공부 기록 연결':'프로젝트 연결'}</h2><p className="my-3 text-sm text-zinc-500">내 기록을 연결할 수 있습니다. 연결은 바로 저장되며, 공개 화면에는 공개한 기록만 표시됩니다.</p>{error&&<div role="alert"><p>{error}</p><button type="button" className={buttonClass} onClick={()=>setRevision(value=>value+1)}>다시 불러오기</button></div>}<ul className="space-y-3">{related.map(row=><li key={row.id} className="flex flex-wrap justify-between gap-3"><Link href={`/write?id=${row.id}`}>{row.title||'제목 없는 기록'}</Link><button type="button" className={buttonClass} disabled={disabled||busy||loading} onClick={()=>void change(row,false)}>연결 해제</button></li>)}</ul>{relatedMore&&!loading&&<button type="button" className={buttonClass} onClick={()=>setRelatedOffset(value=>value+20)}>연결된 기록 더 보기</button>}
    <form className="my-5 flex gap-2" onSubmit={event=>{event.preventDefault();setOffset(0);setCandidates([]);setSearch(query);setRevision(value=>value+1);}}><label className="min-w-0 flex-1"><span className="sr-only">연결할 기록 검색</span><input value={query} onChange={event=>setQuery(event.target.value)} maxLength={100} placeholder="연결할 기록 검색" className="w-full rounded-md border border-zinc-200 p-3 text-sm"/></label><button type="submit" className={buttonClass} disabled={busy}>검색</button></form><ul className="space-y-3">{candidates.map(row=><li key={row.id} className="flex flex-wrap justify-between gap-3"><span>{row.title||'제목 없는 기록'}</span><button type="button" className={buttonClass} disabled={disabled||busy||loading||related.some(item=>item.id===row.id)} onClick={()=>void change(row,true)}>{related.some(item=>item.id===row.id)?'연결됨':'연결'}</button></li>)}</ul>{loading&&<p role="status">기록을 불러오는 중입니다.</p>}{!loading&&!error&&!candidates.length&&<p className="text-sm text-zinc-500">연결할 기록이 없습니다.</p>}{more&&!loading&&!error&&<button type="button" className={`${buttonClass} mt-4`} disabled={busy} onClick={()=>setOffset(value=>value+20)}>후보 더 보기</button>}
  </section>;
}
