'use client';
import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import { useViewer, buttonClass, primaryClass } from './ExploreShell.tsx';
import MarkdownBody from './MarkdownBody.tsx';
import { DraftSaveQueue, draftContent, memberRequest } from '../../lib/workspace-data.ts';
import { parseDraft, detailKeys, type DraftContent, type DraftType } from '../../lib/draft.ts';
import { object, errorMessage, typeNames } from '../../lib/explore-data.ts';
import { ApiRequestError, browserAuth } from '../../lib/browser-auth.ts';
const empty: DraftContent = { record_type: 'project', title: '', body: '', details: {}, tags: [] };
const labels: Record<string, string> = { intro: '소개', goal: '목표', role: '내 역할', tools: '사용 기술', troubleshooting: '문제 해결', result: '결과', topic: '학습 주제', resources: '참고 자료', learned: '배운 내용', practice: '실습', questions: '남은 질문' };
type Image = { id: string; ready: boolean; attached: boolean };
export default function Writer({ initialId }: { initialId?: string }) {
  const viewer = useViewer();
  const [form, setForm] = useState<DraftContent>(empty), [loaded, setLoaded] = useState(!initialId), [busy, setBusy] = useState(false), [saving, setSaving] = useState(false), [conflict, setConflict] = useState(false), [notice, setNotice] = useState(''), [preview, setPreview] = useState(false), [images, setImages] = useState<Image[]>([]), [revision, setRevision] = useState(0), [currentId, setCurrentId] = useState(initialId), [tags, setTags] = useState('');
  const formRef = useRef(form); formRef.current = form;
  const recordVersion = useRef(0), dirty = useRef(false), savingCount = useRef(0), textarea = useRef<HTMLTextAreaElement>(null), alive = useRef(true);
  const queueRef = useRef<DraftSaveQueue | null>(null);
  if (!queueRef.current) queueRef.current = new DraftSaveQueue((path, method, body) => memberRequest(viewer.id!, path, method, body));
  const queue = queueRef.current;
  let signature = JSON.stringify(draftContent(form)); try { signature = JSON.stringify(parseDraft(form)); } catch {}
  dirty.current = signature !== queue.saved && (currentId !== undefined || JSON.stringify(form) !== JSON.stringify(empty));
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  useEffect(() => {
    function unload(event: BeforeUnloadEvent) { if (dirty.current || savingCount.current) { event.preventDefault(); event.returnValue = ''; } }
    function navigate(event: MouseEvent) { const target = event.target instanceof Element ? event.target.closest('a, [data-leave-editor]') : null; if (!target || (!dirty.current && !savingCount.current)) return; if (target instanceof HTMLAnchorElement && (target.target === '_blank' || target.getAttribute('href')?.startsWith('#'))) return; if (!window.confirm('저장되지 않은 변경이 있습니다. 이 화면을 나갈까요?')) { event.preventDefault(); event.stopPropagation(); } }
    window.addEventListener('beforeunload', unload); document.addEventListener('click', navigate, true); return () => { window.removeEventListener('beforeunload', unload); document.removeEventListener('click', navigate, true); };
  }, []);
  useEffect(() => { if (!initialId) return; let active = true; setLoaded(false);
    void (async () => { const draft = await memberRequest(viewer.id!, `/api/drafts/${initialId}`); let version = 0;
      try { const record = object((await memberRequest(viewer.id!, `/api/records/${initialId}`)).data); if (!Number.isSafeInteger(record.version)) throw new Error('발행 버전을 확인하지 못했습니다.'); version = Number(record.version); } catch (error) { if (!(error instanceof ApiRequestError && error.status === 404)) throw error; }
      const photo = object((await memberRequest(viewer.id!, `/api/drafts/${initialId}/images`)).data);
      if (!active) return; const next = queue.adopt(draft.data); if (photo.draft_version !== next.version) throw new Error('다른 화면에서 초안이 변경되었습니다. 다시 불러와주세요.');
      recordVersion.current = version; setForm(draftContent(next)); setTags(next.tags.join(', ')); setImages(readImages(photo.images)); setCurrentId(next.id); setConflict(false); setNotice('초안을 불러왔습니다.'); setLoaded(true);
    })().catch(error => { if (active) setNotice(errorMessage(error)); }); return () => { active = false; };
  }, [initialId, viewer.id, revision]);
  function readImages(value: unknown): Image[] { if (!Array.isArray(value)) throw new Error('사진 응답을 확인하지 못했습니다.'); return value.map(value => { const row = object(value); if (typeof row.id !== 'string' || !/^[0-9a-f-]{36}$/i.test(row.id) || typeof row.ready !== 'boolean' || typeof row.attached !== 'boolean') throw new Error('사진 응답을 확인하지 못했습니다.'); return { id: row.id, ready: row.ready, attached: row.attached }; }); }
  function failed(error: unknown) { if (!alive.current) return; if ((error instanceof ApiRequestError && error.status === 409) || queue.blocked) setConflict(true); setNotice(errorMessage(error)); }
  async function save() { if (conflict) throw new Error('버전 충돌을 먼저 해결해주세요.'); savingCount.current++; setSaving(true); setNotice('초안을 저장하는 중입니다.');
    try { const result = await queue.save(formRef.current); if (!alive.current) return result; setCurrentId(result.id); if (!initialId) window.history.replaceState(null, '', `/write?id=${result.id}`); setNotice(JSON.stringify(parseDraft(formRef.current)) === queue.saved ? '비공개 초안을 저장했습니다.' : '이전 입력을 저장했습니다. 추가 변경을 저장해주세요.'); return result; }
    catch (error) { failed(error); throw error; } finally { savingCount.current--; if (alive.current) setSaving(savingCount.current > 0); }
  }
  useEffect(() => { if (!loaded || busy || conflict || !dirty.current) return; const timer = window.setTimeout(() => { void save().catch(() => {}); }, 10000); return () => window.clearTimeout(timer); }, [form, loaded, busy, conflict]);
  async function publish(visibility: 'public' | 'private') { if (visibility === 'public' && !window.confirm('현재 내용을 누구나 볼 수 있도록 공개 발행할까요?')) return; setBusy(true);
    try { const result = await save(); if (!result) return; const response = await memberRequest(viewer.id!, `/api/drafts/${result.id}/publish`, 'POST', { draft_version: result.version, record_version: recordVersion.current, visibility }); const row = object(response.data); if (!Number.isSafeInteger(row.version) || row.visibility !== visibility) throw new Error('발행 응답을 확인하지 못했습니다.'); recordVersion.current = Number(row.version); setNotice(`${visibility === 'public' ? '공개' : '비공개'} 발행했습니다.${response.image_cleanup_pending ? ' 일부 사진 정리는 재시도가 필요합니다.' : ''}`); }
    catch (error) { failed(error); } finally { if (alive.current) setBusy(false); }
  }
  function insert(before: string, after = '') { const input = textarea.current, start = input?.selectionStart ?? form.body.length, end = input?.selectionEnd ?? start; setForm(previous => ({ ...previous, body: previous.body.slice(0, start) + before + previous.body.slice(start, end) + after + previous.body.slice(end) })); input?.focus(); }
  function changeType(value: DraftType) { if ((Object.values(form.details).some(value => value.trim()) || currentId) && !window.confirm('글 종류를 바꾸면 기존 안내 항목과 프로젝트·공부 연결이 제거됩니다. 계속할까요?')) return; setForm(previous => ({ ...previous, record_type: value, details: {} })); }
  async function refreshImages(id: string) { const data = object((await memberRequest(viewer.id!, `/api/drafts/${id}/images`)).data); setImages(readImages(data.images)); }
  async function complete(id: string, insertBody = true) { const expectedVersion = queue.version; const data = object((await memberRequest(viewer.id!, `/api/images/${id}/complete`, 'POST')).data); if (!Number.isSafeInteger(data.draft_version) || typeof data.url !== 'string' || data.url !== `/api/images/${id}`) throw new Error('사진 완료 응답을 확인하지 못했습니다.'); if (data.draft_version !== expectedVersion + (insertBody ? 1 : 0)) throw new ApiRequestError('다른 화면에서 초안이 변경되었습니다. 입력을 백업하고 서버 내용을 확인해주세요.', 409); queue.version = Number(data.draft_version); if (insertBody) setForm(previous => ({ ...previous, body: `${previous.body}\n\n![기록 사진](${data.url})` })); if (queue.id) await refreshImages(queue.id); }
  async function upload(file: File) { if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024 || !file.size) { setNotice('5MB 이하 JPEG·PNG·WebP 사진을 선택해주세요.'); return; } setBusy(true);
    try { const result = await save(); if (!result) return; const response = object((await memberRequest(viewer.id!, `/api/drafts/${result.id}/images`, 'POST', { draft_version: result.version, mime_type: file.type, byte_size: file.size })).data); if (typeof response.id !== 'string' || typeof response.bucket !== 'string' || typeof response.upload_path !== 'string') throw new Error('사진 예약 응답을 확인하지 못했습니다.'); await refreshImages(result.id); const session = await browserAuth().auth.getSession(); if (session.data.session?.user.id !== viewer.id) throw new Error('로그인 상태가 변경되었습니다.'); const uploaded = await browserAuth().storage.from(response.bucket).upload(response.upload_path, file, { contentType: file.type, upsert: false, cacheControl: '0' }); if (uploaded.error) throw new Error('사진 업로드에 실패했습니다. 예약을 취소하고 다시 업로드해주세요.'); await complete(response.id); setNotice('사진을 추가했습니다. 본문을 저장하면 반영됩니다.'); }
    catch (error) { failed(error); } finally { if (alive.current) setBusy(false); }
  }
  async function imageAction(image: Image, remove: boolean) { if (remove && !window.confirm('이 사진을 초안에서 분리할까요? 발행된 사진은 다음 발행 시 반영됩니다.')) return; setBusy(true);
    try { if (remove) { const data = object((await memberRequest(viewer.id!, `/api/images/${image.id}`, 'DELETE', { draft_version: queue.version })).data); if (!Number.isSafeInteger(data.draft_version)) throw new Error('사진 버전 응답을 확인하지 못했습니다.'); queue.version = Number(data.draft_version); setForm(previous => ({ ...previous, body: previous.body.replace(new RegExp(`!\\[[^\\]\\n]*\\]\\(/api/images/${image.id}\\)`, 'g'), '') })); if (queue.id) await refreshImages(queue.id); setNotice(data.cleanup_pending ? '사진 정리가 일부 지연되었습니다. 다시 시도해주세요.' : '사진을 분리했습니다.'); } else { await complete(image.id, !image.ready); setNotice('사진 완료 처리를 다시 시도했습니다.'); } }
    catch (error) { failed(error); } finally { if (alive.current) setBusy(false); }
  }
  function backup() { const url = URL.createObjectURL(new Blob([JSON.stringify(form, null, 2)], { type: 'application/json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = '취업좀하자-초안-백업.json'; anchor.click(); URL.revokeObjectURL(url); }
  return <main id="main" className="mx-auto max-w-6xl px-5 pt-10 sm:px-8"><div className="mb-8 flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-mono text-zinc-500">글쓰기</p><h1 className="mt-3 text-3xl font-semibold">기록 작성</h1></div><Link href="/archive" className={buttonClass}>내 아카이브</Link></div>
    <div role="status" className="mb-6 text-sm leading-6 text-zinc-600">{notice || '작성 중인 내용은 입력을 멈춘 뒤 10초 후 자동 저장됩니다. 초안은 나만 볼 수 있습니다.'}</div>
    {!loaded || conflict ? <div className="mb-6 flex flex-wrap gap-3"><button className={buttonClass} type="button" onClick={backup}>현재 작성 내용 내려받기</button><button className={buttonClass} type="button" onClick={() => { if (window.confirm('현재 입력을 서버 내용으로 교체할까요? 먼저 작성 내용 내려받기을 권장합니다.')) { dirty.current = false; if (!initialId && currentId) window.location.assign(`/write?id=${currentId}`); else if (initialId) setRevision(value => value + 1); else window.location.assign('/archive'); } }}>최신 서버 내용 불러오기</button></div> : null}{loaded && <>
    <fieldset disabled={busy || conflict} className="min-w-0"><div className="mb-6 flex flex-wrap gap-4"><label className="text-sm">글 종류<select value={form.record_type} onChange={event => changeType(event.target.value as DraftType)} className="ml-3 rounded-md border border-zinc-200 p-2">{Object.entries(typeNames).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="min-w-48 flex-1 text-sm">기술 태그<input value={tags} onChange={event => { setTags(event.target.value); setForm(previous => ({ ...previous, tags: event.target.value.split(',').map(value => value.trim()).filter(Boolean) })); }} placeholder="쉼표로 구분 · 최대 10개" className="mt-2 block w-full rounded-md border border-zinc-200 p-2 sm:mt-0 sm:ml-3 sm:inline-block sm:w-auto" /></label></div>
    <label className="block"><span className="sr-only">글 제목</span><input value={form.title} maxLength={200} onChange={event => setForm(previous => ({ ...previous, title: event.target.value }))} placeholder="기록의 제목을 입력하세요" className="mb-7 w-full border-b border-zinc-200 pb-5 text-2xl font-semibold outline-none" /></label>
    <details className="mb-7 rounded-md border border-zinc-200 p-5"><summary className="cursor-pointer text-sm font-semibold">항목 안내 · 선택 사항</summary><div className="mt-5 grid gap-5 sm:grid-cols-2">{detailKeys[form.record_type].map(key => <label key={key} className="text-sm">{labels[key]}<textarea value={form.details[key] || ''} onChange={event => setForm(previous => ({ ...previous, details: { ...previous.details, [key]: event.target.value } }))} className="mt-2 min-h-24 w-full rounded-md border border-zinc-200 p-3" /></label>)}{form.record_type === 'other' && <p className="text-sm text-zinc-500">기타 기록은 본문을 자유롭게 작성하세요.</p>}</div></details>
    <div className="rounded-md border border-zinc-200"><div className="flex flex-wrap gap-2 border-b border-zinc-200 p-3"><button type="button" className={buttonClass} aria-pressed={!preview} onClick={() => setPreview(false)}>편집</button><button type="button" className={buttonClass} aria-pressed={preview} onClick={() => setPreview(true)}>미리보기</button>{!preview && <>{[['제목', '## ', ''], ['굵게', '**', '**'], ['코드', '\n```text\n', '\n```\n'], ['수식', '$$', '$$'], ['링크', '[링크](', ')']].map(([label, before, after]) => <button key={label} type="button" className={buttonClass} onClick={() => insert(before, after)}>{label}</button>)}</>}</div>{preview ? <div className="min-h-96 p-6"><MarkdownBody body={form.body} /></div> : <label><span className="sr-only">기록 본문</span><textarea ref={textarea} value={form.body} onChange={event => setForm(previous => ({ ...previous, body: event.target.value }))} placeholder="Markdown으로 자유롭게 기록하세요. 코드 블록과 수식을 지원합니다." className="min-h-96 w-full resize-y p-5 font-mono text-sm leading-7 outline-none" /></label>}</div>
    <section className="mt-6 rounded-md border border-zinc-200 p-5"><h2 className="mb-3 text-sm font-semibold">사진</h2><label className="block text-sm text-zinc-600">JPEG·PNG·WebP · 최대 5MB<input type="file" accept="image/jpeg,image/png,image/webp" disabled={saving} className="mt-3 block max-w-full text-sm" onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; if (file) void upload(file); }} /></label>{images.map(image => <div key={image.id} className="mt-3 flex flex-wrap items-center gap-3 text-xs"><span>{!image.attached ? '분리된 사진 · 발행본 참조 또는 정리 대기' : image.ready ? '본문에 사용 가능한 사진' : '완료되지 않은 업로드'}</span>{image.attached && <button type="button" disabled={saving} className={buttonClass} onClick={() => void imageAction(image, false)}>{image.ready ? '원본 정리 재시도' : '완료 재시도'}</button>}<button type="button" disabled={saving} className={buttonClass} onClick={() => void imageAction(image, true)}>{!image.attached ? '정리 재시도' : image.ready ? '사진 분리' : '예약 취소'}</button></div>)}</section>
    </fieldset><div className="mt-7 flex flex-wrap gap-3"><button type="button" className={buttonClass} disabled={busy || saving || conflict} onClick={() => void save().catch(() => {})}>{saving ? '저장 중…' : '초안 저장'}</button><button type="button" className={buttonClass} disabled={busy || saving || conflict} onClick={() => void publish('private')}>비공개 발행</button><button type="button" className={primaryClass} disabled={busy || saving || conflict} onClick={() => void publish('public')}>{busy ? '처리 중…' : '공개 발행'}</button><button type="button" className={buttonClass} onClick={backup}>작성 내용 내려받기</button></div><p className="mt-4 text-xs leading-6 text-zinc-500">초안을 저장해도 이미 발행한 글은 바뀌지 않습니다. 수정한 내용을 반영하려면 다시 발행해주세요.</p></>}
  </main>;
}
